### ISSUE TITLE
1 June Release Checklist

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/ehealth.api#166]
This is checklist for every developer, you need to go cross all services that you responsible of and make sure all boxes is checked.

```
Docs:
- [ ] Repository has meaningful README.md that describes what service does.
- [ ] Service API matches Apiary description.
- [ ] If applicable - there are link to Docker Hub.
- [ ] (if repo is public) Docker Hub page links to `/docs/ENVIRONMENT.md` file and repo.
- [ ] `README.md` contains list of third-party dependencies: eg. PostgreSQL or some NIF lib.

Configuration:
- [ ] All reasonable configuration data is taken from environment variables.
- [ ] `.env` file is up to date.
- [ ] `/docs/ENVIRONMENT.md` file is present and describes configuration options, what do they mean. Examples: [ael.api](https://github.com/Nebo15/ael.api/blob/master/docs/ENVIRONMENT.md), [annon.infra](https://github.com/Nebo15/annon.infra). README.md links to it. (Or place everything in README.md).
- [ ] `LOG_LEVEL` env [is used](https://github.com/Nebo15/ael.api/blob/master/lib/ael_api/application.ex#L14).
- [ ] `ERLANG_COOKIE` is [accepted at start-time](https://github.com/Nebo15/annon.api/blob/master/rel/templates/vm.args.eex#L5).

Logging:
- [ ] Logs are written in JSON format (`logger_json`).
- [ ] Logs does not contain critical data even in DEBUG mode: full dumps of objects that contain it, secrets, tokens, etc. If so - drop log or hide secret from it via Logger configuration (and make sure it's applied).

Security:
- [ ] There are no secrets to any service in repository source code. (If not - delete them and tell me to rotate them.)
- [ ] There are no secrets that is packed to a container in a CI process. (If not - delete them and tell me to rotate them.)

Debugging in production:
- [ ] `:release_tools` in included in application dependencies.
```

For @warehousman @mmiliaieva @AlekzandrV @lymychp:

- [ ] Relative docs (API or spec) are mentioned in README.md of repos

Template for README.md:

```
# Service Name
[![Build Status](https://travis-ci.org/Nebo15/service_name.svg?branch=master)](https://travis-ci.org/Nebo15/service_name) [![Coverage Status](https://coveralls.io/repos/github/Nebo15/service_name/badge.svg?branch=master)](https://coveralls.io/github/Nebo15/service_name?branch=master)

Service name does A, B, C.

## Specification

- [API docs](docs.service_name.apiary.io/)
- [Entity-relation diagram](docs/erd.pdf)
- [Implementation specification]()

## Installation

You can use official Docker container to deploy this service, it can be found on [nebo15/service_name](https://hub.docker.com/r/nebo15/service_name/) Docker Hub.

### Dependencies

- PostgreSQL 9.6 is used as storage back-end.

## Configuration

See [ENVIRONMENT.md](docs/ENVIRONMENT.md).

## License

See [LICENSE.md](LICENSE.md).

```

**Comment by AndrewDryga** [comment]
Public Front-end:
- [ ] Communication with API goes trough Gateway.

**Comment by alexeybondarenko** [comment]
`ENVIRONMENT.md` - is new for our workflow. We usually describe environment variables in Readme.md. Are you sure we need to waste our time for this change?

**Comment by AndrewDryga** [comment]
@alexeybondarenko README.md works fine. But there are should be table with all configs and everybody should know where to look for it.

**Comment by alexeybondarenko** [comment]
@AndrewDryga maybe for API projects - it could be nice to have a separate file. But for frontend project - it is overhead. We usually don't have more than 10 variables, so we can show them all in `Readme.md`. So I don't think that is a required option for production.

**Comment by AndrewDryga** [comment]
@warehousman @mmiliaieva @AlekzandrV:

- [ ] Relative docs (API or spec) are mentioned in README.md of repos

**Comment by AndrewDryga** [comment]
Template for README.md:

```
# Service Name

Service name does A, B, C.

## Specification

- [API docs](docs.service_name.apiary.io/)
- [Entity-relation diagram](docs/erd.pdf)
- [Implementation specification]()

## Installation

You can use official Docker container to deploy this service, it can be found on [nebo15/service_name](https://hub.docker.com/r/nebo15/service_name/) Docker Hub.

### Dependencies

- PostgreSQL 9.6 is used as storage back-end.

## Configuration

See [ENVIRONMENT.md](docs/ENVIRONMENT.md).

## License

See [LICENSE.md](LICENSE.md).

```

**Comment by lymychp** [comment]
- [ ] PRM @PavelVesnin 
- [ ] IL @PavelVesnin 
- [ ] OPS @PavelVesnin 
- [ ] MPI @Samorai 
- [ ] UAdresses @Samorai 
- [ ] man @AndrewDryga 
- [ ] man web @alexeybondarenko 
- [ ] mithrill @gmile 
- [ ] mithrill web @ivchenkodima 
- [ ] ael @PavelVesnin 
- [ ] otp @Samorai 
- [ ] GW @AndrewDryga 
- [ ] GW web @alexeybondarenko 
- [ ] GW status @alexeybondarenko 
- [ ] DS @MBatrak

**Comment by PavelVesnin** [comment]
release_tools -> runtime_tools

**Comment by alexeybondarenko** [comment]
@AndrewDryga, @lymychp maybe we could close this issue?
