### ISSUE TITLE
Deactivate MSP

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#206]
As a MSP owner 
I want to "Provide capability to deactivate MSP. MSP deactivation should lead to employee deactivation, declarations deactivation, divisions deactivation etc." Example: MSP being closed.

- [x] IL.Deactivate legal entity process #536 
- [x] Add mis_verified in legal_entity PRM.DB  #537  
- [x] Change Create/Update Legal Entity process #542
- [x] Change Update LE status on Verify LE by MIS #538
- [x] Verify LE by NHS #539 
- [x] Add mis_verified, nhs_verified in Get Legal Entities #540
- [x] Add mis_verified, nhs_verified in Get Legal Entitiy by ID #541

**Comment by AlekzandrV** [comment]
Tested - passed
