### ISSUE TITLE
Mountain Group

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#217]
Mountain group should be calculated for each MSP division
Relates to #135 
- [x] mountain group should be calculated whenever division is created/updated
- [x] update the division's MG whenever is is updated on uaddresses 
- [x] provide mountain_group #360 - approved in related task
- [x] update mountain_group on settlement uaddresses #412

**Comment by AlekzandrV** [comment]
404 error
Request:
```
curl -X PATCH \
  http://dev.ehealth.world/api/uaddresses/settlements/45e1affb-0234-41c0-adb8-650cd892bb41 \
  -H 'authorization: Bearer MWxkQXZzMFFmWkZyRWF1VE9GTUFxZz09' \
  -H 'content-type: application/json' \
  -d '{
            "mountain_group": "true"
        }'
```

Response:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/settlements/45e1affb-0234-41c0-adb8-650cd892bb41",
        "type": "object",
        "request_id": "t8mcnfasu050j060drtqh1ttmjdjm3rs",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
}
```

**Comment by PavelVesnin** [comment]
@AlekzandrV fixed gateway config

**Comment by AlekzandrV** [comment]
@PavelVesnin The same error
Perhaps the problem here
https://github.com/Nebo15/uaddresses.api/blob/master/lib/uaddresses_api/web/router.ex

**Comment by PavelVesnin** [comment]
@AlekzandrV fixed, deployed and test

**Comment by AlekzandrV** [comment]
@PavelVesnin 
Make district_id as optional parameter

Request:
```
curl -X PATCH \
  http://dev.ehealth.world/api/uaddresses/settlements/45e1affb-0234-41c0-adb8-650cd892bb41 \
  -H 'authorization: Bearer bmZ4c1Y4MFhxb0tuT1NNU1ErSmlNUT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 813343dd-1109-6a8f-c6d7-2f8426eb0492' \
  -d '{
  "mountain_group": "true",
  "region_id": "0cbaccf9-77e2-48a4-94d3-ad3737140476"
}'
```
Response:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/uaddresses/settlements/45e1affb-0234-41c0-adb8-650cd892bb41",
        "type": "object",
        "request_id": "c0ut1lq2tvm1rh30c6ehlu1ceakbab4b",
        "code": 422
    },
    "error": {
        "meta": {
            "url": "http://dev.ehealth.world/settlements/45e1affb-0234-41c0-adb8-650cd892bb41",
            "type": "object",
            "request_id": "c0ut1lq2tvm1rh30c6ehlu1ceakbab4b",
            "code": 422
        },
        "error": {
            "type": "validation_failed",
            "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
            "invalid": [
                {
                    "rules": [
                        {
                            "rule": null,
                            "params": [],
                            "description": "Selected district doesn't exists'"
                        },
                        {
                            "rule": "required",
                            "params": [],
                            "description": "can't be blank"
                        }
                    ],
                    "entry_type": "json_data_property",
                    "entry": "$.district_id"
                }
            ]
        }
    }
}
```

**Comment by PavelVesnin** [comment]
@AlekzandrV it's UAdresses validations. Maybe it's better create another issue for this?

**Comment by PavelVesnin** [comment]
@AlekzandrV set dictrict param as optional.

**Comment by lymychp** [comment]
tested - passed
