### ISSUE TITLE
Plan for 22.05 - 28.05.2017

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#240]
**Plan for 22.05 - 28.05.2017:**
- [x] Finish Legal Entity at last #241 
- [x] Finish Employee at last #239 
- [x] Oauth Flow
- [x] Create declaration request
- [ ] Discuss web hooks
- [x] Capitation Design #215 
- [x] Deploy Legal Entity and Employee to production
- [x] Add context on GW and logic on IL, using new headers #258
