### ISSUE TITLE
Add contexts on GW and context logic on IL

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#258]
As user I should be able to read only the data that I created and create entities with condition of restricting rights by legal_entity_id and user_id.

- [x] Add contexts on GW (x-consumer-id and x-consumer-metadata) #259
- [x] Add logic on IL API
- [x] Get legal entities #262
- [x] Get legal entity by id #265
- [x] Get Employee Requests List #266
- [x] Create Employee Request #308
- [x] Approve/Reject employee request #272 
- [x] Get Divisions #267
- [x] Update Division #268
- [x] Get Employees List #270
- [x] Get Employee Details #271  
- [x] Change 404 on 403 #473
