### ISSUE TITLE
Integrate clinics

### ISSUE THREAD

**Issue by alexeybondarenko** [Nebo15/ehealth.api#284]
- [ ] Integrate clinics
- [ ] Integrate clinic details

Add filters and search by all available query parameters.
- [ ] legal_entity_id
- [ ] type

**Comment by alexeybondarenko** [comment]
- [ ] Add pagination (we could write common component for table with pagination)
