### ISSUE TITLE
[API] Design the address API

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#31]
API that will let consumer to get settlement ID's using region, area, settlement_name parameters. 
1. Data model
2. Private API
3. Public API

**Comment by lymychp** [comment]
Address dictionary from [UkrPost](https://1drv.ms/f/s!Ao-otjqFZQmzg4c2kENZenmP4Q56MA)

**Comment by lymychp** [comment]
- [ ] fix the pagination for all the endpoints. For example, 
`curl -X GET \
  'http://dev.ehealth.world/api/uaddresses/settlements?limit=100' \
  -H 'authorization: Bearer UHdoeVoxOHl4enBsMVVsY1A3SXorQT09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 0f29ad68-96e1-a84c-b6ec-00ee6ae39e43'`
returns >150k records

**Comment by lymychp** [comment]
- [ ] Get Settlements by district - search by settlement_name doesn't work. Below request returns all the records
```
GET /api/uaddresses/details/district/f067ffa8-31ea-42fd-aec0-7655bb817eef/settlements?settlement_name=Будьки HTTP/1.1
Host: dev.ehealth.world
Authorization: Bearer scope_address
Cache-Control: no-cache
Postman-Token: 92e8b31e-30c7-e597-e705-36b281a02974
```
- [ ] Get Settlements by Districts - search by district doesn't work.  Below request returns all the records
```
GET /api/uaddresses/details/district/f067ffa8-31ea-42fd-aec0-7655bb817eef/settlements?settlement_name=Будьки HTTP/1.1
Host: dev.ehealth.world
Authorization: Bearer scope_address
Cache-Control: no-cache
Postman-Token: f228d657-6b9e-d3cd-99ab-e5268e31b38f
```
- [ ] add *get settlement details by ID* endpoint
- [ ] add *get district details by ID* endpoint
- [ ] add *get region details by ID* endpoint
