### ISSUE TITLE
Prepare nhs.admin.web for release

### ISSUE THREAD

**Issue by alexeybondarenko** [Nebo15/ehealth.api#366]
- [x] Replace favicon and appicons with nhs logo
- [ ] Add nhs logo to sidebar
- [x] Add titles to all pages (title, og:title).
- [x] Check Readme.md for all description and env variables
- [x] Check docker hub page for env variable description
- [x] Check all dependencies and components and remove unused
- [x] Check server side rendering
