### ISSUE TITLE
Press conference preparation checklist

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#372]
- [ ] Determine list MIS
- [ ] Check integration on Demo
- [ ] Check integration using MIS UI
- [ ] Fix bugs if found
- [ ] Prepare 3 MSP data sets for each MIS
- [ ] Register MIS on PROD, provide tokens
- [ ] Register 1st data set on Prod
- [ ] Fix bugs if found
- [ ] Train presenter with 2nd dataset on each MIS
- [ ] Record video for each MIS
- [ ] Prepare presenter PC
