### ISSUE TITLE
Add LIKE search in the lists of employees, divisions, legal_entities, parties for NHS admin needs

### ISSUE THREAD

**Issue by alexeybondarenko** [Nebo15/ehealth.api#474]
In NHS admin we need to add a search for the employees. This endpoint has several filter params, such as division_id, legal_entity_id, party_id, etc.

To make this search process simple for the user we need to add the selects for the collections of employees, divisions, etc. We can't preload the full collections because it is too much data. 

So we need a "LIKE search" in this endpoints.

- [x] Search by a part of the name in divisions
- [ ] Search by a part of the name in legal_entities
- [ ] Search by a part of the name in parties.
- [ ] Search by a part of the name in employees

**Comment by AlexKovalevych** [comment]
As discussed with analytics, only divisions search is required, specs: http://docs.ehealthapi1.apiary.io/#reference/internal.-partner-relationship-management/divisions/search-divisions

**Comment by lymychp** [comment]
agreed to merge the implementation of @AlexKovalevych
