### ISSUE TITLE
Resend OTP on declaration request

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#524]
### User story
As a MIS user
I want to be able to resend OTP SMS on the created declaration request via API
So that I can approve declaration requests in case if the patient hasn't received sms from the first time

### Implement Resend OTP service
  - [ ] service [specification](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests-tbd/resend-authorization-otp-on-declaration-request)

### Configure gateway

  - [ ] expose `resend otp` public API endpoint,
  - [ ] add proxy plugin to gateway, proxying all POST requests to `api-svc.il`,
  - [ ] add acl plugin to gateway, with `otp:write` scope required for `POST` (**_authorize user_**),
  - [ ] add auth plugin to gateway, with common configuration (**_authorize user_**).

### Integration Layer processing
  - [ ] Read current auth method:
```
SELECT authentication_method_current
FROM declaration_requests
WHERE id = {:id}
```
Authentication_method_current structure
```
{"type": "OTP", "number": "+380936235985"}
```
  - [ ] Check current auth method value `$.type !== 'OTP'`
* return 422 (`Auth method is not OTP`)
* break

- [ ] Call `OTP initialize` method with number `$.number` from Authentication_method_current structure
