### ISSUE TITLE
Create service Get declaration request by ID

### ISSUE THREAD

**Issue by DPashchenko** [Nebo15/ehealth.api#569]
Service [description](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests-tbd/get-declaration-request-by-id)
Data source: `IL_db.declaration_requests.data`
- [x] expose get-declaration-request-by-id public API endpoint,
- [x]  add proxy plugin to gateway, proxying all GET requests to api-svc.il,
- [x]  add acl plugin to gateway, with declaration_request:read scope required for GET (authorize user),
- [x]  add auth plugin to gateway, with common configuration (authorize user).
