### ISSUE TITLE
Create service Get declaration request list

### ISSUE THREAD

**Issue by DPashchenko** [Nebo15/ehealth.api#575]
Service [description](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests-tbd/get-declaration-requests-list)
Data source: `IL_db.declaration_requests`
Query parameters mapping:

| Parameter                    | Data source  | Data structure|
| --------------------- | ------------| ------------:|
| employee_id                |IL_db.declaration_requests.data|$.employee.id|
| legal_entity_id             |IL_db.declaration_requests.data|$.legal_entity.id|
| status                          |IL_db.declaration_requests.status|                       |

- [x] expose get-declaration-request-list public API endpoint,
- [x]  add proxy plugin to gateway, proxying all GET requests to api-svc.il,
- [x]  add acl plugin to gateway, with declaration_request:read scope required for GET (authorize user),
- [x]  add auth plugin to gateway, with common configuration (authorize user).

**Comment by lymychp** [comment]
@TarasenkoA please test:
- [ ] user cannot get declarations that doesn't belong to his LE

**Comment by TarasenkoA** [comment]
work correctly
request:
```
curl -X GET \
  http://dev.ehealth.world/api/declarations/ \
  -H 'authorization: Bearer ZmVxQmpZd0lHWnpGRWIyL05EWlVydz09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: f4761b33-0c67-87fc-f9f7-fe9be083dba3'
```

For token I have 4 declaration from legal entity in token and 1 declaration for another legal entity. In response i see 4 declaration - it correct logic.
