### ISSUE TITLE
[IL] Search User by Employee Request

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#60]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/internal.-portal-services/users/search-user-by-employee-request)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Search+user)

**Comment by PavelVesnin** [comment]
- [ ] Get email from employee_request
- [ ] Search user by email in auth
- [ ] Return user_id (if found) in response `urgent` attribute

**Comment by PavelVesnin** [comment]
[Get employee_request_by_id](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employee-requests/get-employee-request-by-id)

**Comment by mmiliaieva** [comment]
https://github.com/Nebo15/ehealth.api/issues/109
