### ISSUE TITLE
declarations status historization

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#646]
As a NHS admin
I want to be able to get the detailed stats about declarations: opened/closed over the period
So that it can be used for the management decisions or dashboard stats

- [x] add new table `declaration_status_hstr` to the ops_db  as per [spec](https://github.com/Nebo15/ehealth.api/pull/645)
- [x] change the post/patch operations with declaration - whenever status is created or changed - new record should be added to the`declaration_status_hstr` table
- [x] replicate new table to the reporting_db @vsirius
